### ISSUE TITLE
[Enhancement] x86 Support

### ISSUE THREAD

**Issue by markhewett** [koculu/ZoneTree#46]
It would be nice to have x86 support in the library - I have some other dependencies with native 32-bit libs.

When running on x86 I get this message when disposing the IZoneTree instance.

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.AppendLogEntry(Byte[] keyBytes, Byte[] valueBytes, Int64 opIndex)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.ConsumeQueue()
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.StopWriter(Boolean consumeAll)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.<MarkFrozen>b__37_0()
```

Looking at the code it seems to be related to the CRC32C calculation using hardware support.

**Comment by markhewett** [comment]
Wow! 😍

**Comment by markhewett** [comment]
Testing and getting this now:

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Sse42.X64.Crc32(UInt64 crc, UInt64 data)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.AppendLogEntry(Byte[] keyBytes, Byte[] valueBytes, Int64 opIndex)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.ConsumeQueue()
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.StopWriter(Boolean consumeAll)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.<MarkFrozen>b__37_0()
```

Could be this in `Crc32Computer_SSE42_X86`?

```diff
    public static uint Compute(uint crc, byte[] data)
    {
        var off = 0;
        var len = data.Length;
        while (len >= 4)
        {
-           crc = (uint)Sse42.X64.Crc32(crc, BitConverter.ToUInt32(data, off));
            off += 4;
            len -= 4;
        }

```

**Comment by koculu** [comment]
Fixed on: 
https://github.com/koculu/ZoneTree/releases/tag/release-v1.6.9
