### ISSUE TITLE
X86 - Operation is not supported...

### ISSUE THREAD

**Issue by markhewett** [koculu/ZoneTree#48]
Testing X86 (NuGet 1.6.8) and getting this now:

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Sse42.X64.Crc32(UInt64 crc, UInt64 data)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.AppendLogEntry(Byte[] keyBytes, Byte[] valueBytes, Int64 opIndex)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.ConsumeQueue()
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.StopWriter(Boolean consumeAll)
   at Tenray.ZoneTree.WAL.AsyncCompressedFileSystemWriteAheadLog`2.<MarkFrozen>b__37_0()
```

Could be this in `Crc32Computer_SSE42_X86`?

```diff
    public static uint Compute(uint crc, byte[] data)
    {
        var off = 0;
        var len = data.Length;
        while (len >= 4)
        {
-           crc = (uint)Sse42.X64.Crc32(crc, BitConverter.ToUInt32(data, off));
            off += 4;
            len -= 4;
        }

```

_Originally posted by @markhewett in https://github.com/koculu/ZoneTree/issues/46#issuecomment-1718220832_

**Comment by koculu** [comment]
Thanks, since I committed this without testing, I haven't updated last remaining X64 call.
It is fixed with: https://github.com/koculu/ZoneTree/commit/93a4cfdba84c972c5d32527633ac2131a261f784
